# snmp pkg install
---
- name: apt-update
  hosts: node-1
  tasks:
    - name: apt-update
      apt:
       update_cache: yes
    - name: snmp pkg install
      apt:
       name:
        - snmpd
        - snmp
        - rrdtool
       state: present

# cp /etc/snmp/snmpd.conf
#---
- name: snmpd.conf backup
  hosts: node-1
  tasks:
    - shell: cp /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf.bak
    - shell: ls /etc/snmp/

# snmpd.conf edit
#---
- name: snmpd.conf edit
  hosts: node-1
  tasks:
    - name: snmpd.conf delete
      file:
        path: /etc/snmp/snmpd.conf
        state: absent
    - name: snmpd.conf create
      lineinfile:
         path: /etc/snmp/snmpd.conf
         line: "com2sec local 127.0.0.1 uri\ncom2sec mynetwork 211.237.13.44 uri\n#com2sec mynetwork 0.0.0.0/0.0.0.0 uri\n# group 설정\ngroup MyRWGroup v1 local\ngroup MyRWGroup v2c local\ngroup MyRWGroup usm local\ngroup MyROGroup v1 mynetwork\ngroup MyROGroup v2c mynetwork\ngroup MyROGroup usm mynetwork\ndontLogTCPWrappersConnects true\n#view 설정\nview all included .1 80\naccess MyROGroup \"\" any noauth exact all none none\naccess MyROGroup \"\" any noauth exact all none none\n"
         insertbefore: EOF
         create: yes

# service enable
#---
- name: snmpd service enable
  hosts: node-1
  tasks:
    - shell: systemctl restart snmpd
    - shell: systemctl enable snmpd
    - shell: systemctl status snmpd
      register: shell_result

    - debug:
       var: shell_result.stdout_lines
