---
- hosts: "{{ hosts }}"
  remote_user: ec2-user
  become: true
  tasks:
   - name: old .ssh baskup
     command: cp -Rp /home/TMON/{{ item }}/.ssh /home/TMON/{{ item }}/.ssh_bak 
     with_items:
      - "{{ user }}"
   - name: ssh-authorized add
     template:
       src: ./template/user_keys/ssh-authorized-20211220.pem 
       dest: /home/TMON/{{ item }}/.ssh/ssh-authorized-20211220.pem
     with_items:
      - "{{ user }}"
   - name: config add
     template:
       src: ./template/user_keys/config
       dest: /home/TMON/{{ item }}/.ssh/config
     with_items:
      - "{{ user }}"
   - name: user-authorized change
     template:
       src: ./template/user_keys/authorized_keys
       dest: /home/TMON/{{ item }}/.ssh/authorized_keys
     with_items:
      - "{{ user }}"
   - name: chown set
     command: chown {{ item }}:{{ group }} -R /home/TMON/{{ item }}/.ssh/
     with_items:
      - "{{ user }}"
   - name: chmod set
     command: chmod 400 /home/TMON/{{ item }}/.ssh/ssh-authorized-20211220.pem
     with_items:
      - "{{ user }}"

  vars:
    hosts: "all"
    group: "tmon-dev"
    user:
     - bluecheer86
     - cactusym
     - choebk
     - codebit
     - ellog
     - hwshin
     - iprid123
     - jabberwock
     - jhlee007
     - joonsikez
     - kanghakhan
     - labong
     - orth02
     - purpleline402
     - seunghyun
     - toursoft002
     - toursoft003
     - zephyr